name: nightfalldlp
description: check PR's for sensitive information
inputs:
  git_user:
    description: git user for stuff
    required: true
  git_pass:
    description: git pass for stuff
    required: true
  github_token:
    description: github token for stuff
    required: true

runs: 
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.git_user }}
    - ${{ inputs.git_pass }}
  env:
    GIT_USER: ${{ inputs.git_user }}
    GIT_PASS: ${{ inputs.git_pass }}
    NIGHTFALLDLP_GITHUB_API_TOKEN: ${{ inputs.GITHUB_TOKEN }}

# jobs:
#   nightfalldlp-pr:
#     name: nightfalldlp on Pull Request
#     # inputs:
#     #   git_user:
#     #     description: git user for stuff
#     #     required: true
#     #   git_pass:
#     #     description: git pass for stuff
#     #     required: true
#     runs: 
#       using: 'docker'
#       image: 'Dockerfile'
#       # args:
#       #   - ${{ inputs.git_user }}
#       #   - ${{ inputs.git_pass }}
#       env:
#         GIT_USER: ${{ inputs.git_user }}
#         GIT_PASS: ${{ inputs.git_pass }}
#         NIGHTFALLDLP_GITHUB_API_TOKEN: ${{ inputs.GITHUB_TOKEN }}

#     steps:
#       - name: Download NightfallDLP Action repo (NB - currently private)
#         shell: bash
#         with:
#           GIT_USER: ${{ env.NIGHTFALL_GITHUB_USER }}
#           GIT_PASS: ${{ env.NIGHTFALL_GITHUB_PASS }}
#         run: git clone https://$GIT_USER:$GIT_PASS@github.com/watchtowerai/nightfall_dlp.git

#       - name: Download Go Modules
#         run: go mod download

#       - name: Install nightfalldlp
#         run: |
#           go install ./nightfall_dlp/cmd/nightfalldlp

#       - name: Run nightfalldlp (github-pr-check)
#         continue-on-error: true
#         # env:
#         #   NIGHTFALLDLP_GITHUB_API_TOKEN: ${{ env.GITHUB_TOKEN }}
#         run: |
#           nightfalldlp
