name: nightfalldlp
description: check PR's for sensitive information
runs:
  using: 'Docker'
  image: 'docker://nightfallai/nightfall_dlp:cc2e160e4054f6fbefe367bba458ad208ff90171'
branding:
  icon: 'eye'
  color: 'purple'
