name: nightfalldlp
description: check PR's for sensitive information
runs:
  using: 'Docker'
  image: 'docker://nightfallai/nightfall_dlp:d6ff7e009053063a2ffc05abf5cf0b266b0ab7e3'
branding:
  icon: 'eye'
  color: 'purple'
