name: nightfalldlp
description: check PR's for sensitive information

jobs:
  nightfalldlp-pr:
    name: nightfalldlp on Pull Request
    runs: 
      using: 'docker'
      image: 'Dockerfile'
    steps:
      - name: Download NightfallDLP Action repo (NB - currently private)
        shell: bash
        env:
          GIT_USER: ${{ NIGHTFALL_GITHUB_USER }}
          GIT_PASS: ${{ NIGHTFALL_GITHUB_PASS }}
        run: git clone https://$GIT_USER:$GIT_PASS@github.com/watchtowerai/nightfall_dlp.git

      - name: Download Go Modules
        run: go mod download

      - name: Install nightfalldlp
        run: |
          go install ./nightfall_dlp/cmd/nightfalldlp

      - name: Run nightfalldlp (github-pr-check)
        continue-on-error: true
        env:
          NIGHTFALLDLP_GITHUB_API_TOKEN: ${{ GITHUB_TOKEN }}
        run: |
          nightfalldlp
