name: nightfalldlp
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  nightfalldlp:
    env:
      action_version: nightfallai/nightfall_dlp_action/${{ github.event.ref }}
    name: nightfalldlp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Action
        uses: actions/checkout@v2

      - name: nightfallDLP action step
        uses: ${{ env.action_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIGHTFALL_API_KEY: ${{ secrets.NIGHTFALL_API_KEY }}
          EVENT_BEFORE: ${{ github.event.before }}
