name: nightfalldlp
on: [pull_request]
env:
    nf_git_user: ${{ secrets.NIGHTFALL_GITHUB_USER }}
    nf_git_pass: ${{ secrets.NIGHTFALL_GITHUB_PASS }}
    nightfall_dlp_github_api_token: ${{ secrets.GITHUB_TOKEN }}
    JOSH_TEST: "HEY THERE JOSH"
jobs:
  nightfalldlp-pr:
    name: nightfalldlp on Pull Request
    runs-on: ubuntu-latest
    # env:
    #     GIT_USER: ${{ secrets.NIGHTFALL_GITHUB_USER }}
    #     GIT_PASS: ${{ secrets.NIGHTFALL_GITHUB_PASS }}
    #     NIGHTFALLDLP_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    env:
        nf_git_user: ${{ secrets.NIGHTFALL_GITHUB_USER }}
        nf_git_pass: ${{ secrets.NIGHTFALL_GITHUB_PASS }}
        nightfall_dlp_github_api_token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      # - name: Install go
      #   uses: actions/setup-go@v1
      #   with:
      #     go-version: 1.13

      # - name: Add $GOPATH/bin
      #   run: |
      #     echo ::add-path::$(go env GOPATH)/bin

      # - name: Download repo (and action since it's currently in a private repo)
      #   uses: actions/checkout@v2

      # https://github.com/actions/cache/blob/master/examples.md#go---modules
      - name: Cache Go Modules
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

    #   - name: Update git url (since has private dependency)
    #     shell: bash
        # env:
        #   GIT_USER: ${{ secrets.NIGHTFALL_GITHUB_USER }}
        #   GIT_PASS: ${{ secrets.NIGHTFALL_GITHUB_PASS }}
        # run: |
        #   git config --global url."https://$GIT_USER:$GIT_PASS@github.com/".insteadOf "https://github.com/"

      - name: Download NightfallDLP Action Repo
        shell: bash
        # env:
        #   GIT_USER: ${{ secrets.NIGHTFALL_GITHUB_USER }}
        #   GIT_PASS: ${{ secrets.NIGHTFALL_GITHUB_PASS }}
        run: git clone https://$nf_git_user:$nf_git_pass@github.com/watchtowerai/nightfall_dlp.git
      
      - name: Download Go Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: go mod download

      - name: Setup nightfalldlp
        run: |
          go install ./cmd/nightfalldlp

      # - name: Run nightfalldlp (github-pr-check)
      #   continue-on-error: true
      #   env:
      #     NIGHTFALLDLP_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     nightfalldlp
      - name: nightfallDLP action step
        uses: nightfallai/nightfall_dlp@test-action
        with:
            nf_git_user: ${{ secrets.NIGHTFALL_GITHUB_USER }}
            nf_git_pass: ${{ secrets.NIGHTFALL_GITHUB_PASS }}
            nightfall_dlp_github_api_token: ${{ secrets.GITHUB_TOKEN }}
            JOSH_TEST: ${{ env.JOSH_TEST }}
