name: nightfalldlp
on: [pull_request]
jobs:
  nightfalldlp-pr:
    name: nightfalldlp on Pull Request
    runs-on: ubuntu-latest
    env:
#      nf_git_user: ${{ secrets.NIGHTFALL_GITHUB_USER }}
#      nf_git_pass: ${{ secrets.NIGHTFALL_GITHUB_PASS }}
#      nightfall_dlp_github_api_token: ${{ secrets.GITHUB_TOKEN }}
#      just_a_test: SOME_TESTY_MAN
      GIT_USER: ${{ secrets.GIT_USER }}
      GIT_PASS: ${{ secrets.GIT_PASS }}
      NIGHTFALL_GITHUB_TOKEN: ${{ secrets.NIGHTFALL_GITHUB_TOKEN }}
    steps:
      - name: test 0
        shell: bash
        run: pwd

      - name: Download Nightfall Scanner tool Repo1
        shell: bash
        run: git clone "https://${{ env.GIT_USER }}:${{ env.GIT_PASS }}@github.com/watchtowerai/nightfall_dlp.git" scanner

      - name: Add $GOPATH/bin
        run: |
          echo ::add-path::$(go env GOPATH)/bin

      - name: Download repo (and action since it's currently in a private repo)
        uses: actions/checkout@v2

      - name: test a
        shell: bash
        run: pwd && ls && ls .. && cd scanner

      # https://github.com/actions/cache/blob/master/examples.md#go---modules
      - name: Cache Go Modules
        id: cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: test 2
        shell: bash
        run: pwd

      - name: Update git url (since has private dependency)
        shell: bash
        run: |
          git config --global url."https://$GIT_USER:$GIT_PASS@github.com/".insteadOf "https://github.com/"

      - name: test 3
        shell: bash
        run: pwd

      - name: Download Go Modules
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: cd scanner && go mod download

      - name: test 4
        shell: bash
        run: pwd

      - name: Setup nightfalldlp
        run: |
          cd scanner && go install "./cmd/nightfalldlp"

      - name: Run nightfalldlp (github-pr-check)
        continue-on-error: true
        #        env:
        #          NIGHTFALLDLP_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd && ls && ls .. && NIGHTFALL_GITHUB_TOKEN="helpidty" nightfalldlp

#      - name: nightfallDLP action step
#        uses: nightfallai/nightfall_dlp@test
#        with:
#          nf_git_user: ${{ secrets.NIGHTFALL_GITHUB_USER }}
#          nf_git_pass: ${{ secrets.NIGHTFALL_GITHUB_PASS }}
#          nightfall_dlp_github_api_token: ${{ secrets.GITHUB_TOKEN }}
#          JOSH_TEST: ${{ env.JOSH_TEST }}
#          TOMATHY: TIMOTHY TOMATHY TIMMINS





#name: nightfalldlp
#on: [pull_request, push]
##env:
##    nf_git_user: ${{ secrets.NIGHTFALL_GITHUB_USER }}
##    nf_git_pass: ${{ secrets.NIGHTFALL_GITHUB_PASS }}
##    nightfall_dlp_github_api_token: ${{ secrets.GITHUB_TOKEN }}
##    JOSH_TEST: "HEY THERE JOSH"
##    anotha: ${{ secrets.GIT_USER }}
#jobs:
#  nightfalldlp-pr:
#    name: nightfalldlp on Pull Request
#    runs-on: ubuntu-latest
#    env:
#        nf_git_user: ${{ secrets.NIGHTFALL_GITHUB_USER }}
#        nf_git_pass: ${{ secrets.NIGHTFALL_GITHUB_PASS }}
#        nightfall_dlp_github_api_token: ${{ secrets.GITHUB_TOKEN }}
#        just_a_test: SOME_TESTY_MAN
#        GIT_USER: ${{ secrets.GIT_USER }}
#        GIT_PASS: ${{ secrets.GIT_PASS }}
#        NIGHTFALL_GITHUB_TOKEN: ${{ secrets.NIGHTFALL_GITHUB_TOKEN }}
#    steps:
#      - name: Download Nightfall Scanner tool Repo1
#        shell: bash
#        run: git clone "https://${{ env.GIT_USER }}:${{ env.GIT_PASS }}@github.com/watchtowerai/nightfall_dlp.git" nightfall
#
#      - name: Add $GOPATH/bin
#        run: |
#          echo ::add-path::$(go env GOPATH)/bin
#
#      # https://github.com/actions/cache/blob/master/examples.md#go---modules
#      - name: Cache Go Modules
#        id: cache
#        uses: actions/cache@v1
#        with:
#          path: ~/go/pkg/mod
#          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
#          restore-keys: |
#            ${{ runner.os }}-go-
#
#      - name: testing
#        shell: bash
#        run: ls
#
#      - name: checkout nightfall_dlp project
#        shell: bash
#        run: ls && cd nightfall && ls
#
#      - name: Update git url (since has private dependency)
#        shell: bash
#        run: |
#          git config --global url."https://$GIT_USER:$GIT_PASS@github.com/".insteadOf "https://github.com/"
#
#      - name: Download Go Modules
#        if: steps.cache.outputs.cache-hit != 'true'
#        shell: bash
#        run: ls && cd nightfall && echo 1 && ls && pwd && go mod download
#
#      - name: Setup nightfalldlp
#        run: |
#          cd nightfall && go install "./cmd/nightfalldlp"
##          go env && ls $GOPATH/bin && echo 11111 &&
##          cd nightfall && go build ./cmd/nightfalldlp -o nightfall_dlp_main -v
#
##      - name: Stuff
##        shell: bash
##        run: echo $GOPATH && ls $GOPATH/bin
#
#      - name: Run nightfalldlp (github-pr-check)
#        continue-on-error: true
##        env:
##          NIGHTFALLDLP_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          NIGHTFALL_GITHUB_TOKEN="helpidty" nightfalldlp
##          NIGHTFALL_GITHUB_TOKEN="${{ env.NIGHTFALL_GITHUB_TOKEN}}" nightfalldlp
##          ls && pwd && cd nightfall && nightfall_dlp_main
##          ls && pwd && cd nightfall && nightfalldlp
##          ls && pwd && nightfalldlp
#
#      - name: nightfallDLP action step
#        uses: nightfallai/nightfall_dlp@test
#        with:
#            nf_git_user: ${{ secrets.NIGHTFALL_GITHUB_USER }}
#            nf_git_pass: ${{ secrets.NIGHTFALL_GITHUB_PASS }}
#            nightfall_dlp_github_api_token: ${{ secrets.GITHUB_TOKEN }}
#            JOSH_TEST: ${{ env.JOSH_TEST }}
#            TOMATHY: TIMOTHY TOMATHY TIMMINS
