name: nightfalldlp
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  nightfalldlp:
    name: nightfalldlp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Action
        uses: actions/checkout@v2

      - name: Echo Head Ref
        run: echo ::set-env name=action_version::nightfallai/nightfall_dp_action@$GITHUB_HEAD_REF

      - name: nightfallDLP action step
        uses: ${{ env.action_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIGHTFALL_API_KEY: ${{ secrets.NIGHTFALL_API_KEY }}
          EVENT_BEFORE: ${{ github.event.before }}
